import os
from dotenv import load_dotenv

load_dotenv()

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")
DATABASE_URL = os.getenv("DATABASE_URL")

LIVEKIT_URL = os.getenv("LIVEKIT_URL")
LIVEKIT_API_KEY = os.getenv("LIVEKIT_API_KEY")
LIVEKIT_API_SECRET = os.getenv("LIVEKIT_API_SECRET")

RESEND_FROM_EMAIL = os.getenv("RESEND_FROM_EMAIL")

DUFFEL_API_KEY = os.getenv("DUFFEL_API_KEY")

RAZORPAY_KEY_ID = os.getenv("RAZORPAY_KEY_ID")
RAZORPAY_KEY_SECRET = os.getenv("RAZORPAY_KEY_SECRET")

RESEND_API_KEY = os.getenv("RESEND_API_KEY")
EMAIL_FROM = os.getenv("RESEND_FROM_EMAIL")

GROQ_API_KEY = os.getenv("GROQ_API_KEY")
GROQ_STT_MODEL = os.getenv("GROQ_STT_MODEL")
GROQ_TTS_MODEL = os.getenv("GROQ_TTS_MODEL")
GROQ_TTS_VOICE = os.getenv("GROQ_TTS_VOICE")
GROQ_CHAT_MODEL = os.getenv("GROQ_CHAT_MODEL")